In [13]:
import torch
import numpy as np

In [8]:
a = torch.tensor([1,2,3,4,5], dtype=torch.int32)
a_col = a.view(5,1)

In [9]:
a_col

tensor([[1],
        [2],
        [3],
        [4],
        [5]], dtype=torch.int32)

In [10]:
a_col = a.view(-1,1)
a_col

tensor([[1],
        [2],
        [3],
        [4],
        [5]], dtype=torch.int32)

In [11]:
a = torch.Tensor([0,1,2,3,4,5])
a_col = a.view(6,1)
a_col

tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.]])

In [14]:
numpy_array = np.array([0,1,2,3,4])
torch_tensor = torch.from_numpy(numpy_array)
back_to_numpy = torch_tensor.numpy()

In [15]:
numpy_array

array([0, 1, 2, 3, 4])

In [16]:
torch_tensor

tensor([0, 1, 2, 3, 4], dtype=torch.int32)

In [17]:
back_to_numpy

array([0, 1, 2, 3, 4])

In [18]:
u = torch.tensor([1,2,3,-1])
v = u + 1

In [19]:
v

tensor([2, 3, 4, 0])

In [22]:
u = torch.tensor([1,2])
v = torch.tensor([3,2])
z = u*v 
z

tensor([3, 4])

In [24]:
u = torch.tensor([1,2])
v = torch.tensor([3,1])
z = torch.dot(u,v) 
z

tensor(5)

In [51]:
a = torch.tensor([1,-1,1,-1])
#torch.mean(a)
mean_a = a.mean()
mean_a

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long