In [1]:
import torch

In [3]:
a = [[1,2,3],[4,5,6],[7,8,9]]
A = torch.tensor(a)
A

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [4]:
A.ndimension()

2

In [ ]:
A.shape()

In [7]:
A.size()

torch.Size([3, 3])

In [8]:
A.numel()

9

In [10]:
x = torch.tensor([[1,0],[0,1]])
y = torch.tensor([[2,1],[1,2]])
z = x + y
z

tensor([[3, 1],
        [1, 3]])

In [14]:
z = y*2
z

tensor([[4, 2],
        [2, 4]])

In [13]:
z = x * y
z

tensor([[2, 0],
        [0, 2]])

In [16]:
a = torch.tensor([[0,1,1],[1,0,1]])
b = torch.tensor([[1,1],[1,1],[-1,1]])
c = torch.mm(a,b)
c

tensor([[0, 2],
        [0, 2]])

In [18]:
A = torch.tensor([[0, 1, 1], [1, 0, 1]])
B = torch.tensor([[1, 1], [1, 1], [-1, 1]])
A_times_B = torch.mm(A,B)
A_times_B

tensor([[0, 2],
        [0, 2]])