In [2]:
import torch
from torch.nn import Linear

In [3]:
torch.manual_seed(1)

In [4]:
model = Linear(in_features=2, out_features=1)

In [5]:
list(model.parameters())

[Parameter containing:
 tensor([[ 0.3643, -0.3121]], requires_grad=True),
 Parameter containing:
 tensor([-0.1371], requires_grad=True)]

In [9]:
model = Linear(in_features=2, out_features=1)
X=torch.tensor([[1.0,3.0]])
yhat = model(X)
yhat

tensor([[-0.6200]], grad_fn=<AddmmBackward0>)

In [10]:
X=torch.tensor([[1.0,1.0],[1.0,2.0],[1.0,3.0]])
yhat= model(X)
yhat

tensor([[-0.0689],
        [-0.3444],
        [-0.6200]], grad_fn=<AddmmBackward0>)